---
output: 
  stevetemplates::article:
    latex_engine: xelatex
    fig_caption: true
#bibliography: master.bib
title: "Group Project"
author:
- name: Y3877831
  affiliation: University of York
geometry: margin=3in
fontsize: 11pt
fontfamily: mathpazo
bibliography: refs.bib
css: nature-cell-biology.csl
# spacing: double
endnote: no
abstract: "This document provides an introduction to R Markdown, argues for its benefits, and presents a sample manuscript template intended for an academic audience. I include basic syntax to R Markdown and a minimal working example of how the analysis itself can be conducted within R with the `knitr` package."
keywords: "Atherosclerosis, Wnt Signalling Pathway, Beta-catenin, Shear Stress, Human Umbilical Vein Endothelial Cells (HUVECs), Angiopoietin-2, Axin, Thrombospondin-1."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r load-pkgs}
library(tidyverse) # Load the tidyverse. Functions are used for tidying data and creating plots via ggplot2.

library(kableExtra) # Load kableExtra. Table generation.

library(wordcountaddin) # Load wordcountaddin. Counts words and characters in text in an R markdown document.
```

# Introduction

\@Li2014-mx

```{=plain}
<!-- 
Description of the background to the investigation 
An account of relevant literature
A clear statement of the major aims (or hypotheses) of the investigation
What is the question your project is asking and why it is a good question?
It should explain the basic nature of the problem and how your work seeks to extend scientific knowledge in the area. 
Be concise. Space is limited, so make sure that the literature you cover is directly relevant to your project. 
Start broad, then focus in.
End with a clear statement of aims (and/or hypotheses).-->
```

------------------------------------------------------------------------

# Methods

```{=plain}
<!-- 
A clear and concise description of the experimental methods used in the investigation.
Sufficient detail should be provided to enable the experiments to be reproduced.
Data figures and analysis should not be included in this section.-->
```
## HUVECs {.unnumbered}

## Orbital Shaker {.unnumbered}

Plates were placed on an orbital shaker to rotate at 210 rpm for 72 hours.

## RNA Extraction {.unnumbered}

## cDNA Synthesis {.unnumbered}

Verso cDNA Synthesis Kit

## qPCR {.unnumbered}

RNEasy Mini Kit

------------------------------------------------------------------------

# Results

```{=html}
<!-- 
Clear and well-structured description of findings 
Appropriate narrative of the experimental rationale and the major conclusions 
May include descriptions of problem solving and troubleshooting
Well-prepared and consistently presented tables and figures 
Numbered tables and figures with legends (captions).
Legends should provide enough information to allow the reader to understand the table/figure.
Get your figures and tables ready first
Use enough text to provide a clear narrative through those figures and tables
Do start with some basic results
Highlight the key findings, but don’t discuss them
Make sure statistics are reported in the correct format
Few references -->
```

------------------------------------------------------------------------

# Discussion

```{=html}
<!-- Do not simply recapitulate the results
Explore the wider meaning of the results
To what extent has your investigation addressed the aims provided in the introduction?
How have your findings advanced understanding of the problem under investigation?
How do your findings relate to previous studies in this area?
Based on your findings, what new investigations might be conducted?
Work in parallel with the introduction
Don’t just give a commentary of the results
How does your work compare with previous work?
Why might you have got different results?
How could you improve the project? (Don’t just say ‘collect more data’!) -->
```
<!-- In future look at vascular repair with scratch wound assay.  -->

------------------------------------------------------------------------

# Acknowledgements

------------------------------------------------------------------------

```{=tex}
\begin{flushright}
Word Count: `r word_count("report.Rmd")`. (report)

Word Count: `r word_count("main.Rmd")`. (main body - abstract)
\end{flushright}
```
# References

```{=html}
<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->
```
